import 'dart:async';
import 'dart:convert';

import 'package:ebookstore/model/Json_Model.dart';

import 'package:http/http.dart' as http;

class TrendingServiceAPI {
  String API_Key = "d02f498529msh0f9fee89c8a6c15p146328jsn20b45d7fe16c";

  List Book = [];
  Future<List<Items>> getBooks(String trendnig) async {
  String apiUrl = "https://www.googleapis.com/books/v1/volumes?q=${trendnig}";
    final response = await http.get(Uri.parse(apiUrl));

    if (response.statusCode == 200) {
      final data = json.decode(response.body);
      Autogenerated booksData = Autogenerated.fromJson(data);
      return booksData.items ?? [];
    } else {
      throw Exception('Failed to load books');
    }
  }
}
