import 'dart:convert';
import 'package:ebookstore/model/Json_Model.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

class SearchProvider with ChangeNotifier {
  String searchText = '';
  List<Items> books = [];
  List<Items> allBooks = [];

  void search(String username) {
    searchText = username;
    // updateData();
    getBooks(searchText);
    notifyListeners();
  }

  void updateData() {
    if (searchText.isEmpty) {
      books = List.from(allBooks);
    } else {
      books = allBooks
          .where((element) => element.volumeInfo!.title!.toLowerCase().startsWith(searchText.toLowerCase()))
          .toList();
    }
    notifyListeners();
  }

  Future<void> getBooks(String category) async {
    String apiUrl = "https://www.googleapis.com/books/v1/volumes?q=$category&maxResults=10&startIndex=1";
    final response = await http.get(Uri.parse(apiUrl));

    if (response.statusCode == 200) {
      final data = json.decode(response.body);
      Autogenerated booksData = Autogenerated.fromJson(data);
      allBooks = booksData.items ?? [];
      updateData(); // Ensure data is updated after fetching
    } else {
      throw Exception('Failed to load books');
    }
  }
}
