

class Autogenerated {
  String? _kind;
  int? _totalItems;
  List<Items>? _items;

  Autogenerated({String? kind, int? totalItems, List<Items>? items}) {
    if (kind != null) {
      this._kind = kind;
    }
    if (totalItems != null) {
      this._totalItems = totalItems;
    }
    if (items != null) {
      this._items = items;
    }
  }

  String? get kind => _kind;
  set kind(String? kind) => _kind = kind;
  int? get totalItems => _totalItems;
  set totalItems(int? totalItems) => _totalItems = totalItems;
  List<Items>? get items => _items;
  set items(List<Items>? items) => _items = items;

  Autogenerated.fromJson(Map<String, dynamic> json) {
    _kind = json['kind'];
    _totalItems = json['totalItems'];
    if (json['items'] != null) {
      _items = <Items>[];
      json['items'].forEach((v) {
        _items!.add(new Items.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['kind'] = this._kind;
    data['totalItems'] = this._totalItems;
    if (this._items != null) {
      data['items'] = this._items!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Items {
  String? _kind;
  String? _id;
  String? _etag;
  String? _selfLink;
  VolumeInfo? _volumeInfo;
  SaleInfo? _saleInfo;
  AccessInfo? _accessInfo;
  SearchInfo? _searchInfo;

  Items(
      {String? kind,
      String? id,
      String? etag,
      String? selfLink,
      VolumeInfo? volumeInfo,
      SaleInfo? saleInfo,
      AccessInfo? accessInfo,
      SearchInfo? searchInfo}) {
    if (kind != null) {
      this._kind = kind;
    }
    if (id != null) {
      this._id = id;
    }
    if (etag != null) {
      this._etag = etag;
    }
    if (selfLink != null) {
      this._selfLink = selfLink;
    }
    if (volumeInfo != null) {
      this._volumeInfo = volumeInfo;
    }
    if (saleInfo != null) {
      this._saleInfo = saleInfo;
    }
    if (accessInfo != null) {
      this._accessInfo = accessInfo;
    }
    if (searchInfo != null) {
      this._searchInfo = searchInfo;
    }
  }

  String? get kind => _kind;
  set kind(String? kind) => _kind = kind;
  String? get id => _id;
  set id(String? id) => _id = id;
  String? get etag => _etag;
  set etag(String? etag) => _etag = etag;
  String? get selfLink => _selfLink;
  set selfLink(String? selfLink) => _selfLink = selfLink;
  VolumeInfo? get volumeInfo => _volumeInfo;
  set volumeInfo(VolumeInfo? volumeInfo) => _volumeInfo = volumeInfo;
  SaleInfo? get saleInfo => _saleInfo;
  set saleInfo(SaleInfo? saleInfo) => _saleInfo = saleInfo;
  AccessInfo? get accessInfo => _accessInfo;
  set accessInfo(AccessInfo? accessInfo) => _accessInfo = accessInfo;
  SearchInfo? get searchInfo => _searchInfo;
  set searchInfo(SearchInfo? searchInfo) => _searchInfo = searchInfo;

  Items.fromJson(Map<String, dynamic> json) {
    _kind = json['kind'];
    _id = json['id'];
    _etag = json['etag'];
    _selfLink = json['selfLink'];
    _volumeInfo = json['volumeInfo'] != null
        ? new VolumeInfo.fromJson(json['volumeInfo'])
        : null;
    _saleInfo = json['saleInfo'] != null
        ? new SaleInfo.fromJson(json['saleInfo'])
        : null;
    _accessInfo = json['accessInfo'] != null
        ? new AccessInfo.fromJson(json['accessInfo'])
        : null;
    _searchInfo = json['searchInfo'] != null
        ? new SearchInfo.fromJson(json['searchInfo'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['kind'] = this._kind;
    data['id'] = this._id;
    data['etag'] = this._etag;
    data['selfLink'] = this._selfLink;
    if (this._volumeInfo != null) {
      data['volumeInfo'] = this._volumeInfo!.toJson();
    }
    if (this._saleInfo != null) {
      data['saleInfo'] = this._saleInfo!.toJson();
    }
    if (this._accessInfo != null) {
      data['accessInfo'] = this._accessInfo!.toJson();
    }
    if (this._searchInfo != null) {
      data['searchInfo'] = this._searchInfo!.toJson();
    }
    return data;
  }
}

class VolumeInfo {
  String? _title;
  String? _subtitle;
  List<String>? _authors;
  String? _publisher;
  String? _publishedDate;
  String? _description;
  List<IndustryIdentifiers>? _industryIdentifiers;
  ReadingModes? _readingModes;
  int? _pageCount;
  String? _printType;
  List<String>? _categories;
  String? _maturityRating;
  bool? _allowAnonLogging;
  String? _contentVersion;
  PanelizationSummary? _panelizationSummary;
  ImageLinks? _imageLinks;
  String? _language;
  String? _previewLink;
  String? _infoLink;
  String? _canonicalVolumeLink;
  int? _averageRating;
  int? _ratingsCount;

  VolumeInfo({
    String? title,
    String? subtitle,
    List<String>? authors,
    String? publisher,
    String? publishedDate,
    String? description,
    List<IndustryIdentifiers>? industryIdentifiers,
    ReadingModes? readingModes,
    int? pageCount,
    String? printType,
    List<String>? categories,
    String? maturityRating,
    bool? allowAnonLogging,
    String? contentVersion,
    PanelizationSummary? panelizationSummary,
    ImageLinks? imageLinks,
    String? language,
    String? previewLink,
    String? infoLink,
    String? canonicalVolumeLink,
    int? averageRating,
    int? ratingsCount,
  }) {
    _title = title;
    _subtitle = subtitle;
    _authors = authors;
    _publisher = publisher;
    _publishedDate = publishedDate;
    _description = description;
    _industryIdentifiers = industryIdentifiers;
    _readingModes = readingModes;
    _pageCount = pageCount;
    _printType = printType;
    _categories = categories;
    _maturityRating = maturityRating;
    _allowAnonLogging = allowAnonLogging;
    _contentVersion = contentVersion;
    _panelizationSummary = panelizationSummary;
    _imageLinks = imageLinks;
    _language = language;
    _previewLink = previewLink;
    _infoLink = infoLink;
    _canonicalVolumeLink = canonicalVolumeLink;
    _averageRating = averageRating;
    _ratingsCount = ratingsCount;
  }

  String? get title => _title;
  set title(String? title) => _title = title;
  String? get subtitle => _subtitle;
  set subtitle(String? subtitle) => _subtitle = subtitle;
  List<String>? get authors => _authors;
  set authors(List<String>? authors) => _authors = authors;
  String? get publisher => _publisher;
  set publisher(String? publisher) => _publisher = publisher;
  String? get publishedDate => _publishedDate;
  set publishedDate(String? publishedDate) => _publishedDate = publishedDate;
  String? get description => _description;
  set description(String? description) => _description = description;
  List<IndustryIdentifiers>? get industryIdentifiers => _industryIdentifiers;
  set industryIdentifiers(List<IndustryIdentifiers>? industryIdentifiers) =>
      _industryIdentifiers = industryIdentifiers;
  ReadingModes? get readingModes => _readingModes;
  set readingModes(ReadingModes? readingModes) => _readingModes = readingModes;
  int? get pageCount => _pageCount;
  set pageCount(int? pageCount) => _pageCount = pageCount;
  String? get printType => _printType;
  set printType(String? printType) => _printType = printType;
  List<String>? get categories => _categories;
  set categories(List<String>? categories) => _categories = categories;
  String? get maturityRating => _maturityRating;
  set maturityRating(String? maturityRating) =>
      _maturityRating = maturityRating;
  bool? get allowAnonLogging => _allowAnonLogging;
  set allowAnonLogging(bool? allowAnonLogging) =>
      _allowAnonLogging = allowAnonLogging;
  String? get contentVersion => _contentVersion;
  set contentVersion(String? contentVersion) =>
      _contentVersion = contentVersion;
  PanelizationSummary? get panelizationSummary => _panelizationSummary;
  set panelizationSummary(PanelizationSummary? panelizationSummary) =>
      _panelizationSummary = panelizationSummary;
  ImageLinks? get imageLinks => _imageLinks;
  set imageLinks(ImageLinks? imageLinks) => _imageLinks = imageLinks;
  String? get language => _language;
  set language(String? language) => _language = language;
  String? get previewLink => _previewLink;
  set previewLink(String? previewLink) => _previewLink = previewLink;
  String? get infoLink => _infoLink;
  set infoLink(String? infoLink) => _infoLink = infoLink;
  String? get canonicalVolumeLink => _canonicalVolumeLink;
  set canonicalVolumeLink(String? canonicalVolumeLink) =>
      _canonicalVolumeLink = canonicalVolumeLink;
  int? get averageRating => _averageRating;
  set averageRating(int? averageRating) => _averageRating = averageRating;
  int? get ratingsCount => _ratingsCount;
  set ratingsCount(int? ratingsCount) => _ratingsCount = ratingsCount;

  VolumeInfo.fromJson(Map<String, dynamic> json) {
    _title = json['title'];
    _subtitle = json['subtitle'];
    _authors =
        json['authors'] != null ? List<String>.from(json['authors']) : null;
    _publisher = json['publisher'];
    _publishedDate = json['publishedDate'];
    _description = json['description'];
    if (json['industryIdentifiers'] != null) {
      _industryIdentifiers = <IndustryIdentifiers>[];
      json['industryIdentifiers'].forEach((v) {
        _industryIdentifiers!.add(new IndustryIdentifiers.fromJson(v));
      });
    }
    _readingModes = json['readingModes'] != null
        ? ReadingModes.fromJson(json['readingModes'])
        : null;
    _pageCount = json['pageCount'];
    _printType = json['printType'];
    _categories = json['categories'] != null
        ? List<String>.from(json['categories'])
        : null;
    _maturityRating = json['maturityRating'];
    _allowAnonLogging = json['allowAnonLogging'];
    _contentVersion = json['contentVersion'];
    _panelizationSummary = json['panelizationSummary'] != null
        ? PanelizationSummary.fromJson(json['panelizationSummary'])
        : null;
    _imageLinks = json['imageLinks'] != null
        ? ImageLinks.fromJson(json['imageLinks'])
        : null;
    _language = json['language'];
    _previewLink = json['previewLink'];
    _infoLink = json['infoLink'];
    _canonicalVolumeLink = json['canonicalVolumeLink'];
    _averageRating = json['averageRating'];
    _ratingsCount = json['ratingsCount'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['title'] = _title;
    data['subtitle'] = _subtitle;
    data['authors'] = _authors;
    data['publisher'] = _publisher;
    data['publishedDate'] = _publishedDate;
    data['description'] = _description;
    if (_industryIdentifiers != null) {
      data['industryIdentifiers'] =
          _industryIdentifiers!.map((v) => v.toJson()).toList();
    }
    if (_readingModes != null) {
      data['readingModes'] = _readingModes!.toJson();
    }
    data['pageCount'] = _pageCount;
    data['printType'] = _printType;
    data['categories'] = _categories;
    data['maturityRating'] = _maturityRating;
    data['allowAnonLogging'] = _allowAnonLogging;
    data['contentVersion'] = _contentVersion;
    if (_panelizationSummary != null) {
      data['panelizationSummary'] = _panelizationSummary!.toJson();
    }
    if (_imageLinks != null) {
      data['imageLinks'] = _imageLinks!.toJson();
    }
    data['language'] = _language;
    data['previewLink'] = _previewLink;
    data['infoLink'] = _infoLink;
    data['canonicalVolumeLink'] = _canonicalVolumeLink;
    data['averageRating'] = _averageRating;
    data['ratingsCount'] = _ratingsCount;
    return data;
  }
}

class IndustryIdentifiers {
  String? _type;
  String? _identifier;

  IndustryIdentifiers({String? type, String? identifier}) {
    if (type != null) {
      this._type = type;
    }
    if (identifier != null) {
      this._identifier = identifier;
    }
  }

  String? get type => _type;
  set type(String? type) => _type = type;
  String? get identifier => _identifier;
  set identifier(String? identifier) => _identifier = identifier;

  IndustryIdentifiers.fromJson(Map<String, dynamic> json) {
    _type = json['type'];
    _identifier = json['identifier'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['type'] = this._type;
    data['identifier'] = this._identifier;
    return data;
  }
}

class ReadingModes {
  bool? _text;
  bool? _image;

  ReadingModes({bool? text, bool? image}) {
    if (text != null) {
      this._text = text;
    }
    if (image != null) {
      this._image = image;
    }
  }

  bool? get text => _text;
  set text(bool? text) => _text = text;
  bool? get image => _image;
  set image(bool? image) => _image = image;

  ReadingModes.fromJson(Map<String, dynamic> json) {
    _text = json['text'];
    _image = json['image'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['text'] = this._text;
    data['image'] = this._image;
    return data;
  }
}

class PanelizationSummary {
  bool? _containsEpubBubbles;
  bool? _containsImageBubbles;

  PanelizationSummary({bool? containsEpubBubbles, bool? containsImageBubbles}) {
    if (containsEpubBubbles != null) {
      this._containsEpubBubbles = containsEpubBubbles;
    }
    if (containsImageBubbles != null) {
      this._containsImageBubbles = containsImageBubbles;
    }
  }

  bool? get containsEpubBubbles => _containsEpubBubbles;
  set containsEpubBubbles(bool? containsEpubBubbles) =>
      _containsEpubBubbles = containsEpubBubbles;
  bool? get containsImageBubbles => _containsImageBubbles;
  set containsImageBubbles(bool? containsImageBubbles) =>
      _containsImageBubbles = containsImageBubbles;

  PanelizationSummary.fromJson(Map<String, dynamic> json) {
    _containsEpubBubbles = json['containsEpubBubbles'];
    _containsImageBubbles = json['containsImageBubbles'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['containsEpubBubbles'] = this._containsEpubBubbles;
    data['containsImageBubbles'] = this._containsImageBubbles;
    return data;
  }
}

class ImageLinks {
  String? _smallThumbnail;
  String? _thumbnail;

  ImageLinks({String? smallThumbnail, String? thumbnail}) {
    if (smallThumbnail != null) {
      this._smallThumbnail = smallThumbnail;
    }
    if (thumbnail != null) {
      this._thumbnail = thumbnail;
    }
  }

  String? get smallThumbnail => _smallThumbnail;
  set smallThumbnail(String? smallThumbnail) =>
      _smallThumbnail = smallThumbnail;
  String? get thumbnail => _thumbnail;
  set thumbnail(String? thumbnail) => _thumbnail = thumbnail;

  ImageLinks.fromJson(Map<String, dynamic> json) {
    _smallThumbnail = json['smallThumbnail'];
    _thumbnail = json['thumbnail'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['smallThumbnail'] = this._smallThumbnail;
    data['thumbnail'] = this._thumbnail;
    return data;
  }
}

class SaleInfo {
  String? _country;
  String? _saleability;
  bool? _isEbook;

  SaleInfo({String? country, String? saleability, bool? isEbook}) {
    if (country != null) {
      this._country = country;
    }
    if (saleability != null) {
      this._saleability = saleability;
    }
    if (isEbook != null) {
      this._isEbook = isEbook;
    }
  }

  String? get country => _country;
  set country(String? country) => _country = country;
  String? get saleability => _saleability;
  set saleability(String? saleability) => _saleability = saleability;
  bool? get isEbook => _isEbook;
  set isEbook(bool? isEbook) => _isEbook = isEbook;

  SaleInfo.fromJson(Map<String, dynamic> json) {
    _country = json['country'];
    _saleability = json['saleability'];
    _isEbook = json['isEbook'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['country'] = this._country;
    data['saleability'] = this._saleability;
    data['isEbook'] = this._isEbook;
    return data;
  }
}

class AccessInfo {
  String? _country;
  String? _viewability;
  bool? _embeddable;
  bool? _publicDomain;
  String? _textToSpeechPermission;
  Epub? _epub;
  Epub? _pdf;
  String? _webReaderLink;
  String? _accessViewStatus;
  bool? _quoteSharingAllowed;

  AccessInfo(
      {String? country,
      String? viewability,
      bool? embeddable,
      bool? publicDomain,
      String? textToSpeechPermission,
      Epub? epub,
      Epub? pdf,
      String? webReaderLink,
      String? accessViewStatus,
      bool? quoteSharingAllowed}) {
    if (country != null) {
      this._country = country;
    }
    if (viewability != null) {
      this._viewability = viewability;
    }
    if (embeddable != null) {
      this._embeddable = embeddable;
    }
    if (publicDomain != null) {
      this._publicDomain = publicDomain;
    }
    if (textToSpeechPermission != null) {
      this._textToSpeechPermission = textToSpeechPermission;
    }
    if (epub != null) {
      this._epub = epub;
    }
    if (pdf != null) {
      this._pdf = pdf;
    }
    if (webReaderLink != null) {
      this._webReaderLink = webReaderLink;
    }
    if (accessViewStatus != null) {
      this._accessViewStatus = accessViewStatus;
    }
    if (quoteSharingAllowed != null) {
      this._quoteSharingAllowed = quoteSharingAllowed;
    }
  }

  String? get country => _country;
  set country(String? country) => _country = country;
  String? get viewability => _viewability;
  set viewability(String? viewability) => _viewability = viewability;
  bool? get embeddable => _embeddable;
  set embeddable(bool? embeddable) => _embeddable = embeddable;
  bool? get publicDomain => _publicDomain;
  set publicDomain(bool? publicDomain) => _publicDomain = publicDomain;
  String? get textToSpeechPermission => _textToSpeechPermission;
  set textToSpeechPermission(String? textToSpeechPermission) =>
      _textToSpeechPermission = textToSpeechPermission;
  Epub? get epub => _epub;
  set epub(Epub? epub) => _epub = epub;
  Epub? get pdf => _pdf;
  set pdf(Epub? pdf) => _pdf = pdf;
  String? get webReaderLink => _webReaderLink;
  set webReaderLink(String? webReaderLink) => _webReaderLink = webReaderLink;
  String? get accessViewStatus => _accessViewStatus;
  set accessViewStatus(String? accessViewStatus) =>
      _accessViewStatus = accessViewStatus;
  bool? get quoteSharingAllowed => _quoteSharingAllowed;
  set quoteSharingAllowed(bool? quoteSharingAllowed) =>
      _quoteSharingAllowed = quoteSharingAllowed;

  AccessInfo.fromJson(Map<String, dynamic> json) {
    _country = json['country'];
    _viewability = json['viewability'];
    _embeddable = json['embeddable'];
    _publicDomain = json['publicDomain'];
    _textToSpeechPermission = json['textToSpeechPermission'];
    _epub = json['epub'] != null ? new Epub.fromJson(json['epub']) : null;
    _pdf = json['pdf'] != null ? new Epub.fromJson(json['pdf']) : null;
    _webReaderLink = json['webReaderLink'];
    _accessViewStatus = json['accessViewStatus'];
    _quoteSharingAllowed = json['quoteSharingAllowed'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['country'] = this._country;
    data['viewability'] = this._viewability;
    data['embeddable'] = this._embeddable;
    data['publicDomain'] = this._publicDomain;
    data['textToSpeechPermission'] = this._textToSpeechPermission;
    if (this._epub != null) {
      data['epub'] = this._epub!.toJson();
    }
    if (this._pdf != null) {
      data['pdf'] = this._pdf!.toJson();
    }
    data['webReaderLink'] = this._webReaderLink;
    data['accessViewStatus'] = this._accessViewStatus;
    data['quoteSharingAllowed'] = this._quoteSharingAllowed;
    return data;
  }
}

class Epub {
  bool? _isAvailable;
  String? _acsTokenLink;

  Epub({bool? isAvailable, String? acsTokenLink}) {
    if (isAvailable != null) {
      this._isAvailable = isAvailable;
    }
    if (acsTokenLink != null) {
      this._acsTokenLink = acsTokenLink;
    }
  }

  bool? get isAvailable => _isAvailable;
  set isAvailable(bool? isAvailable) => _isAvailable = isAvailable;
  String? get acsTokenLink => _acsTokenLink;
  set acsTokenLink(String? acsTokenLink) => _acsTokenLink = acsTokenLink;

  Epub.fromJson(Map<String, dynamic> json) {
    _isAvailable = json['isAvailable'];
    _acsTokenLink = json['acsTokenLink'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['isAvailable'] = this._isAvailable;
    data['acsTokenLink'] = this._acsTokenLink;
    return data;
  }
}

class SearchInfo {
  String? _textSnippet;

  SearchInfo({String? textSnippet}) {
    if (textSnippet != null) {
      this._textSnippet = textSnippet;
    }
  }

  String? get textSnippet => _textSnippet;
  set textSnippet(String? textSnippet) => _textSnippet = textSnippet;

  SearchInfo.fromJson(Map<String, dynamic> json) {
    _textSnippet = json['textSnippet'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['textSnippet'] = this._textSnippet;
    return data;
  }
}
